/**
 * Exercise name → animated GIF URL mapping
 * Source: ExerciseDB (https://exercisedb.dev) — open source, no watermarks
 */

const gifMap: Record<string, string> = {
  // Chest
  'Barbell Bench Press': 'https://static.exercisedb.dev/media/EIeI8Vf.gif',
  'Incline Barbell Bench Press': 'https://static.exercisedb.dev/media/3TZduzM.gif',
  'Decline Barbell Bench Press': 'https://static.exercisedb.dev/media/GrO65fd.gif',
  'Dumbbell Bench Press': 'https://static.exercisedb.dev/media/SpYC0Kp.gif',
  'Incline Dumbbell Bench Press': 'https://static.exercisedb.dev/media/ns0SIbU.gif',
  'Dumbbell Fly': 'https://static.exercisedb.dev/media/yz9nUhF.gif',
  'Incline Dumbbell Fly': 'https://static.exercisedb.dev/media/ESOd5Pl.gif',
  'Cable Fly': 'https://static.exercisedb.dev/media/xLYSdtg.gif',
  'Machine Chest Press': 'https://static.exercisedb.dev/media/T0yTjgW.gif',
  'Push-Up': 'https://static.exercisedb.dev/media/I4hDWkc.gif',
  'Dips (Chest)': 'https://static.exercisedb.dev/media/9WTm7dq.gif',

  // Back
  'Barbell Row': 'https://static.exercisedb.dev/media/eZyBC3j.gif',
  'Dumbbell Row': 'https://static.exercisedb.dev/media/BJ0Hz5L.gif',
  'Pendlay Row': 'https://static.exercisedb.dev/media/r0z6xzQ.gif',
  'Seated Cable Row': 'https://static.exercisedb.dev/media/fUBheHs.gif',
  'T-Bar Row': 'https://static.exercisedb.dev/media/aaXr7ld.gif',
  'Pull-Up': 'https://static.exercisedb.dev/media/lBDjFxJ.gif',
  'Chin-Up': 'https://static.exercisedb.dev/media/T2mxWqc.gif',
  'Lat Pulldown': 'https://static.exercisedb.dev/media/eYnzaCm.gif',
  'Straight-Arm Pulldown': 'https://static.exercisedb.dev/media/x69MAlq.gif',
  'Deadlift': 'https://static.exercisedb.dev/media/ila4NZS.gif',
  'Rack Pull': 'https://static.exercisedb.dev/media/za9Ni4z.gif',

  // Legs
  'Barbell Squat': 'https://static.exercisedb.dev/media/qXTaZnJ.gif',
  'Front Squat': 'https://static.exercisedb.dev/media/zG0zs85.gif',
  'Leg Press': 'https://static.exercisedb.dev/media/10Z2DXU.gif',
  'Hack Squat': 'https://static.exercisedb.dev/media/Qa55kX1.gif',
  'Bulgarian Split Squat': 'https://static.exercisedb.dev/media/qx4fgX7.gif',
  'Lunges': 'https://static.exercisedb.dev/media/RRWFUcw.gif',
  'Romanian Deadlift': 'https://static.exercisedb.dev/media/wQ2c4XD.gif',
  'Leg Curl': 'https://static.exercisedb.dev/media/17lJ1kr.gif',
  'Leg Extension': 'https://static.exercisedb.dev/media/my33uHU.gif',
  'Calf Raise': 'https://static.exercisedb.dev/media/ykUOVze.gif',
  'Seated Calf Raise': 'https://static.exercisedb.dev/media/ktsFQAZ.gif',
  'Hip Thrust': 'https://static.exercisedb.dev/media/aWedzZX.gif',
  'Goblet Squat': 'https://static.exercisedb.dev/media/yn8yg1r.gif',
  'Sumo Deadlift': 'https://static.exercisedb.dev/media/KgI0tqW.gif',

  // Shoulders
  'Overhead Press': 'https://static.exercisedb.dev/media/wdRZISl.gif',
  'Dumbbell Shoulder Press': 'https://static.exercisedb.dev/media/znQUdHY.gif',
  'Arnold Press': 'https://static.exercisedb.dev/media/Xy4jlWA.gif',
  'Lateral Raise': 'https://static.exercisedb.dev/media/DsgkuIt.gif',
  'Front Raise': 'https://static.exercisedb.dev/media/3eGE2JC.gif',
  'Reverse Fly': 'https://static.exercisedb.dev/media/EAs3xL9.gif',
  'Cable Lateral Raise': 'https://static.exercisedb.dev/media/goJ6ezq.gif',
  'Upright Row': 'https://static.exercisedb.dev/media/UDlhcO8.gif',
  'Shrugs': 'https://static.exercisedb.dev/media/NJzBsGJ.gif',
  'Barbell Shrugs': 'https://static.exercisedb.dev/media/dG7tG5y.gif',
  'Machine Shoulder Press': 'https://static.exercisedb.dev/media/67n3r98.gif',

  // Arms
  'Barbell Curl': 'https://static.exercisedb.dev/media/25GPyDY.gif',
  'Dumbbell Curl': 'https://static.exercisedb.dev/media/NbVPDMW.gif',
  'Hammer Curl': 'https://static.exercisedb.dev/media/slDvUAU.gif',
  'Preacher Curl': 'https://static.exercisedb.dev/media/jivWf8n.gif',
  'Concentration Curl': 'https://static.exercisedb.dev/media/gvsWLQw.gif',
  'Cable Curl': 'https://static.exercisedb.dev/media/G08RZcQ.gif',
  'Tricep Pushdown': 'https://static.exercisedb.dev/media/3ZflifB.gif',
  'Overhead Tricep Extension': 'https://static.exercisedb.dev/media/NN8nSNT.gif',
  'Skull Crusher': 'https://static.exercisedb.dev/media/h8LFzo9.gif',
  'Close-Grip Bench Press': 'https://static.exercisedb.dev/media/J6Dx1Mu.gif',
  'Dips (Triceps)': 'https://static.exercisedb.dev/media/X6C6i5Y.gif',
  'Kickbacks': 'https://static.exercisedb.dev/media/W6PxUkg.gif',

  // Core
  'Plank': 'https://static.exercisedb.dev/media/VBAWRPG.gif',
  'Crunch': 'https://static.exercisedb.dev/media/TFqbd8t.gif',
  'Hanging Leg Raise': 'https://static.exercisedb.dev/media/I3tsCnC.gif',
  'Cable Crunch': 'https://static.exercisedb.dev/media/WW95auq.gif',
  'Ab Wheel Rollout': 'https://static.exercisedb.dev/media/xnInPfE.gif',
  'Russian Twist': 'https://static.exercisedb.dev/media/XVDdcoj.gif',
  'Dead Bug': 'https://static.exercisedb.dev/media/iny3m5y.gif',
  'Side Plank': 'https://static.exercisedb.dev/media/RKjH6Lt.gif',
  'Decline Sit-Up': 'https://static.exercisedb.dev/media/QLL2gdc.gif',

  // Migration template exercises
  'Incline Dumbbell Press': 'https://static.exercisedb.dev/media/ns0SIbU.gif',
  'Decline Barbell Press': 'https://static.exercisedb.dev/media/GrO65fd.gif',
  'Cable Chest Fly (Low to High)': 'https://static.exercisedb.dev/media/FVmZVhk.gif',
  'Cable Chest Fly (High to Low)': 'https://static.exercisedb.dev/media/7saC5zz.gif',
  'Dumbbell Pullover': 'https://static.exercisedb.dev/media/yz9nUhF.gif',
  'Dumbbell Flat Bench Press': 'https://static.exercisedb.dev/media/SpYC0Kp.gif',
  'Barbell Bent-Over Row': 'https://static.exercisedb.dev/media/eZyBC3j.gif',
  'Weighted Pull-Up': 'https://static.exercisedb.dev/media/lBDjFxJ.gif',
  'Conventional Barbell Deadlift': 'https://static.exercisedb.dev/media/ila4NZS.gif',
  'Straight Arm Lat Pulldown': 'https://static.exercisedb.dev/media/x69MAlq.gif',
  'Dumbbell Single Arm Row': 'https://static.exercisedb.dev/media/BJ0Hz5L.gif',
  'Lat Pulldown (Wide Grip)': 'https://static.exercisedb.dev/media/eYnzaCm.gif',
  'Back Extension (Weighted)': 'https://static.exercisedb.dev/media/ila4NZS.gif',
  'Barbell Back Squat': 'https://static.exercisedb.dev/media/qXTaZnJ.gif',
  'Barbell Front Squat': 'https://static.exercisedb.dev/media/zG0zs85.gif',
  'Walking Dumbbell Lunge': 'https://static.exercisedb.dev/media/RRWFUcw.gif',
  'Leg Curl Machine': 'https://static.exercisedb.dev/media/17lJ1kr.gif',
  'Standing Calf Raise': 'https://static.exercisedb.dev/media/ykUOVze.gif',
  'Leg Extension Machine': 'https://static.exercisedb.dev/media/my33uHU.gif',
  'Bulgarian Split Squat (Dumbbell)': 'https://static.exercisedb.dev/media/qx4fgX7.gif',
  'Hip Thrust (Barbell)': 'https://static.exercisedb.dev/media/aWedzZX.gif',
  'Overhead Barbell Press (Standing)': 'https://static.exercisedb.dev/media/wdRZISl.gif',
  'Dumbbell Lateral Raise': 'https://static.exercisedb.dev/media/DsgkuIt.gif',
  'Seated Dumbbell Shoulder Press': 'https://static.exercisedb.dev/media/znQUdHY.gif',
  'Barbell Upright Row': 'https://static.exercisedb.dev/media/UDlhcO8.gif',
  'Reverse Pec Deck Fly': 'https://static.exercisedb.dev/media/myfUsKf.gif',
  'Tricep Rope Pushdown': 'https://static.exercisedb.dev/media/3ZflifB.gif',
  'Overhead Tricep Cable Extension': 'https://static.exercisedb.dev/media/NN8nSNT.gif',
  'Barbell Bicep Curl': 'https://static.exercisedb.dev/media/25GPyDY.gif',
  'Dumbbell Hammer Curl': 'https://static.exercisedb.dev/media/slDvUAU.gif',
  'Close Grip Barbell Bench Press': 'https://static.exercisedb.dev/media/J6Dx1Mu.gif',
  'Dumbbell Incline Curl': 'https://static.exercisedb.dev/media/NbVPDMW.gif',
  'Skull Crusher (EZ Bar)': 'https://static.exercisedb.dev/media/h8LFzo9.gif',
  'Cable Overhead Curl': 'https://static.exercisedb.dev/media/G08RZcQ.gif',
  'Tricep Dip (Weighted)': 'https://static.exercisedb.dev/media/X6C6i5Y.gif',
  'Cable Bicep Curl': 'https://static.exercisedb.dev/media/G08RZcQ.gif',
  'Glute Ham Raise': 'https://static.exercisedb.dev/media/aWedzZX.gif',
  'Reverse Hyperextension': 'https://static.exercisedb.dev/media/ila4NZS.gif',
}

export function getExerciseGif(exerciseName: string): string | null {
  return gifMap[exerciseName] ?? null
}
